### PR TITLE
Adding host()

### PR DESCRIPTION
**Pull request by mannypamintuan**
This incorporates the suggestions by @DavidTPate:
https://github.com/hapijs/joi/pull/1356#issuecomment-344292124

- Adds 'host' to the internals object

@ankitsinghaniyaz, at your convenience, please review.

### CODE REVIEW

**Comment by mannypamintuan** [comment]
The latest additions do the following:
-Add 'host()' to 'string'
-Add unit tests

@ankitsinghaniyaz, at your convenience, please review.

**Comment by ankitsinghaniyaz** [comment]
Awesome, I just did the same thing but never mind. 🍷 
The changes are almost identical. I will reset my changes and merge your PR. 👍

**Comment by mannypamintuan** [comment]
@ankitsinghaniyaz It was great to collaborate with you, great minds think alike ;)
🤜 🤛

**Comment by ankitsinghaniyaz** [comment]
Same here. I think the adding of `host` was just one part on the issue https://github.com/hapijs/hapi/issues/3667#issuecomment-343832876

Let's collborate on the next steps as well.

**Pull request merged**
